'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { useClassroom } from '@/components/teacher-shell'
import { apiFetch } from '@/lib/api'
import styles from './solidlab.module.css'

type Topic = { id:string;slug:string;tag:string;num:string;title:string;subtitle:string;info:string;shape_key:string;game_type:string;is_published:boolean }
type Question = { id:string;topic_id:string;prompt:string;option_a:string;option_b:string;option_c:string;option_d:string;answer:string;hint:string }
type ScoreRow = { id:string;number:number;prefix:string;first_name:string;last_name:string;active:boolean;score:number }

export function SolidLabTeacherManager(){
  const {selectedId,selectedClassroom}=useClassroom()
  const [topics,setTopics]=useState<Topic[]>([]),[questions,setQuestions]=useState<Question[]>([]),[scores,setScores]=useState<ScoreRow[]>([])
  const [selectedTopic,setSelectedTopic]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const [options,setOptions]=useState(['','','','']),[answerIndex,setAnswerIndex]=useState(0)

  const load=useCallback(async()=>{if(!selectedId){setTopics([]);return}setLoading(true);setError('');try{const d=await apiFetch<{topics:Topic[];questions:Question[];scoreboard:ScoreRow[]}>(`/api/teacher/solidlab?classroomId=${encodeURIComponent(selectedId)}`);setTopics(d.topics);setQuestions(d.questions);setScores(d.scoreboard);setSelectedTopic((v)=>d.topics.some(t=>t.id===v)?v:(d.topics[0]?.id||''))}catch(e){setError(e instanceof Error?e.message:'โหลด SolidLab ไม่สำเร็จ')}finally{setLoading(false)}},[selectedId])
  useEffect(()=>{void load()},[load])
  const visibleQuestions=useMemo(()=>questions.filter(q=>q.topic_id===selectedTopic),[questions,selectedTopic])

  async function seed(){if(!selectedId)return;setLoading(true);try{await apiFetch('/api/teacher/solidlab',{method:'POST',body:JSON.stringify({action:'seed',classroomId:selectedId})});await load()}catch(e){setError(e instanceof Error?e.message:'สร้างตัวอย่างไม่สำเร็จ')}finally{setLoading(false)}}
  async function addTopic(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedId)return;const f=new FormData(e.currentTarget);const form=e.currentTarget;try{await apiFetch('/api/teacher/solidlab',{method:'POST',body:JSON.stringify({action:'create-topic',classroomId:selectedId,title:f.get('title'),slug:f.get('slug'),tag:f.get('tag'),num:f.get('num'),subtitle:f.get('subtitle'),info:f.get('info'),shapeKey:f.get('shapeKey'),gameType:f.get('gameType'),isPublished:true})});form.reset();await load()}catch(err){setError(err instanceof Error?err.message:'เพิ่มบทเรียนไม่สำเร็จ')}}
  async function toggle(t:Topic){try{await apiFetch('/api/teacher/solidlab',{method:'POST',body:JSON.stringify({action:'update-topic',topicId:t.id,isPublished:!t.is_published})});await load()}catch(e){setError(e instanceof Error?e.message:'เปลี่ยนสถานะไม่สำเร็จ')}}
  async function removeTopic(t:Topic){if(!confirm(`ลบบทเรียน “${t.title}” พร้อมโจทย์และคะแนนของบทเรียนนี้หรือไม่?`))return;try{await apiFetch('/api/teacher/solidlab',{method:'POST',body:JSON.stringify({action:'delete-topic',topicId:t.id})});await load()}catch(e){setError(e instanceof Error?e.message:'ลบบทเรียนไม่สำเร็จ')}}
  async function addQuestion(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedTopic)return;const f=new FormData(e.currentTarget);const form=e.currentTarget;const answer=options[answerIndex];try{await apiFetch('/api/teacher/solidlab',{method:'POST',body:JSON.stringify({action:'create-question',topicId:selectedTopic,prompt:f.get('prompt'),optionA:options[0],optionB:options[1],optionC:options[2],optionD:options[3],answer,hint:f.get('hint'),explanation:f.get('explanation')})});form.reset();setOptions(['','','','']);setAnswerIndex(0);await load()}catch(err){setError(err instanceof Error?err.message:'เพิ่มโจทย์ไม่สำเร็จ')}}
  async function removeQuestion(id:string){if(!confirm('ลบโจทย์ข้อนี้หรือไม่?'))return;try{await apiFetch('/api/teacher/solidlab',{method:'POST',body:JSON.stringify({action:'delete-question',questionId:id})});await load()}catch(e){setError(e instanceof Error?e.message:'ลบโจทย์ไม่สำเร็จ')}}

  if(!selectedClassroom)return <div className="card empty">กรุณาสร้างและเลือกห้องเรียนก่อน</div>
  return <div className={styles.lab}>
    <div><h1 className="page-title">3D + มินิเกม — {selectedClassroom.name}</h1><p className="page-subtitle">SolidLab ที่เชื่อมสิทธิ์ห้องเรียน คะแนน และบัญชีนักเรียนเข้ากับ Supabase เดิม</p></div>
    {error&&<div className="message message-error">{error}</div>}
    <section className="card"><div className="row" style={{justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>ชุดบทเรียน SolidLab</h2><p className="muted">เริ่มได้เร็วด้วย 4 หน่วยจากไฟล์ SolidLab เดิม</p></div><button className="btn btn-primary" disabled={loading} onClick={seed}>สร้าง/เติมบทเรียนตัวอย่าง 4 หน่วย</button></div></section>

    <section className="card"><h2 style={{marginTop:0}}>เพิ่มบทเรียน 3D</h2><form className="stack" onSubmit={addTopic}><div className="grid-2"><label>ชื่อบทเรียน<input name="title" required placeholder="เช่น ลูกบาศก์และทรงสี่เหลี่ยม"/></label><label>slug<input name="slug" required placeholder="cube-basic"/></label></div><div className="grid-2"><label>เลขหน่วย<input name="num" placeholder="05"/></label><label>TAG<input name="tag" placeholder="A05"/></label></div><label>ชื่อหน่วย<input name="subtitle" placeholder="หน่วยที่ 5 — ..."/></label><label>คำอธิบาย<textarea name="info" rows={2}/></label><div className="grid-2"><label>รูปทรง<select name="shapeKey"><option value="cube">ลูกบาศก์</option><option value="prism">ปริซึม/พีระมิด</option><option value="cylinder">ทรงกระบอก/กรวย</option><option value="sphere">ทรงกลม</option></select></label><label>โหมดเกม<select name="gameType"><option value="spin">หมุนดูรูปทรง</option><option value="fold">พับ/คลี่</option></select></label></div><button className="btn btn-primary">เพิ่มบทเรียน</button></form></section>

    <section className="card"><h2 style={{marginTop:0}}>บทเรียนของห้องนี้</h2>{topics.length?<div className="stack">{topics.map(t=><div className="row" key={t.id} style={{justifyContent:'space-between',borderBottom:'1px solid var(--border)',padding:'10px 0',gap:10,flexWrap:'wrap'}}><div><strong>{t.num||'--'} · {t.title}</strong><div className="muted">{t.slug} · {questions.filter(q=>q.topic_id===t.id).length} ข้อ · {t.is_published?'เผยแพร่':'ซ่อน'}</div></div><div className="row"><button className="btn btn-secondary btn-sm" onClick={()=>{setSelectedTopic(t.id);document.getElementById('question-form')?.scrollIntoView({behavior:'smooth'})}}>จัดการโจทย์</button><button className="btn btn-ghost btn-sm" onClick={()=>toggle(t)}>{t.is_published?'ซ่อน':'เผยแพร่'}</button><button className="btn btn-danger btn-sm" onClick={()=>removeTopic(t)}>ลบ</button></div></div>)}</div>:<div className="empty">ยังไม่มีบทเรียน กด “สร้าง/เติมบทเรียนตัวอย่าง 4 หน่วย” ได้เลย</div>}</section>

    <section className="card" id="question-form"><h2 style={{marginTop:0}}>คลังโจทย์มินิเกม</h2><label>บทเรียน<select value={selectedTopic} onChange={e=>setSelectedTopic(e.target.value)}>{topics.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>{selectedTopic&&<><form className="stack" onSubmit={addQuestion} style={{marginTop:14}}><label>คำถาม<textarea name="prompt" required rows={2}/></label>{options.map((v,i)=><label key={i}>ตัวเลือก {String.fromCharCode(65+i)}<input required value={v} onChange={e=>setOptions(arr=>arr.map((x,n)=>n===i?e.target.value:x))}/></label>)}<label>คำตอบที่ถูก<select value={answerIndex} onChange={e=>setAnswerIndex(Number(e.target.value))}>{options.map((_,i)=><option key={i} value={i}>ตัวเลือก {String.fromCharCode(65+i)}</option>)}</select></label><label>คำใบ้<input name="hint"/></label><label>คำอธิบายหลังตอบ<textarea name="explanation" rows={2}/></label><button className="btn btn-primary">เพิ่มโจทย์</button></form><div className="stack" style={{marginTop:18}}>{visibleQuestions.map((q,i)=><div key={q.id} style={{padding:'12px',border:'1px solid var(--border)',borderRadius:12}}><div className="row" style={{justifyContent:'space-between',gap:10}}><strong>{i+1}. {q.prompt}</strong><button className="btn btn-danger btn-sm" onClick={()=>removeQuestion(q.id)}>ลบ</button></div><div className="muted">A {q.option_a} · B {q.option_b} · C {q.option_c} · D {q.option_d}</div><div style={{marginTop:5}}>เฉลย: <strong>{q.answer}</strong></div></div>)}</div></>}</section>

    <section className="card"><h2 style={{marginTop:0}}>คะแนนนักเรียน</h2>{scores.length?<div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>อันดับ</th><th>เลขที่</th><th>ชื่อ</th><th>คะแนน</th></tr></thead><tbody>{scores.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{s.number}</td><td>{s.prefix}{s.first_name} {s.last_name}</td><td><strong>{s.score}</strong></td></tr>)}</tbody></table></div>:<div className="empty">ยังไม่มีนักเรียนหรือคะแนน</div>}</section>
  </div>
}
