'use client'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useClassroom } from '@/components/teacher-shell'
import styles from './comic.module.css'

type Slide={id:string;title:string;description:string;is_published:boolean;page_count:number}
export function ComicSlideManager(){
  const {selectedId,selectedClassroom}=useClassroom();const [slides,setSlides]=useState<Slide[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState('')
  const load=useCallback(async()=>{if(!selectedId){setSlides([]);return}try{const r=await fetch(`/api/teacher/slides?classroomId=${encodeURIComponent(selectedId)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'โหลดสไลด์ไม่สำเร็จ');setSlides(d.slides||[])}catch(e){setError(e instanceof Error?e.message:'โหลดสไลด์ไม่สำเร็จ')}},[selectedId]);useEffect(()=>{void load()},[load])
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedId)return;const form=e.currentTarget;const fd=new FormData(form);const input=form.elements.namedItem('pages') as HTMLInputElement;const files=Array.from(input.files||[]).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));if(!files.length){setError('กรุณาเลือกภาพอย่างน้อย 1 หน้า');return}setLoading(true);setError('');setProgress(`กำลังอัปโหลดหน้า 1/${files.length}`);try{const first=new FormData();first.set('classroomId',selectedId);first.set('title',String(fd.get('title')||''));first.set('description',String(fd.get('description')||''));first.set('sortOrder',String(fd.get('sortOrder')||0));first.set('isPublished',fd.get('isPublished')==='on'?'true':'false');first.set('file',files[0]);let r=await fetch('/api/teacher/slides',{method:'POST',body:first});let d=await r.json();if(!r.ok)throw new Error(d.error||'สร้างชุดสไลด์ไม่สำเร็จ');const id=d.material.id;for(let i=1;i<files.length;i++){setProgress(`กำลังอัปโหลดหน้า ${i+1}/${files.length}`);const page=new FormData();page.set('file',files[i]);r=await fetch(`/api/teacher/slides/${id}/page`,{method:'POST',body:page});d=await r.json();if(!r.ok)throw new Error(d.error||`อัปโหลดหน้า ${i+1} ไม่สำเร็จ`)}setProgress('อัปโหลดครบแล้ว');form.reset();await load()}catch(e){setError(e instanceof Error?e.message:'อัปโหลดสไลด์ไม่สำเร็จ')}finally{setLoading(false);setTimeout(()=>setProgress(''),2500)}}
  async function addPages(id:string,files:FileList|null){if(!files?.length)return;const sorted=Array.from(files).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));setLoading(true);try{for(let i=0;i<sorted.length;i++){setProgress(`กำลังเพิ่มหน้า ${i+1}/${sorted.length}`);const fd=new FormData();fd.set('file',sorted[i]);const r=await fetch(`/api/teacher/slides/${id}/page`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'เพิ่มหน้าไม่สำเร็จ')}await load()}catch(e){setError(e instanceof Error?e.message:'เพิ่มหน้าไม่สำเร็จ')}finally{setLoading(false);setProgress('')}}
  async function remove(s:Slide){if(!confirm(`ลบชุด “${s.title}” และไฟล์ทุกหน้าหรือไม่?`))return;try{const r=await fetch(`/api/teacher/slides/${s.id}`,{method:'DELETE'});const d=await r.json();if(!r.ok)throw new Error(d.error||'ลบไม่สำเร็จ');await load()}catch(e){setError(e instanceof Error?e.message:'ลบไม่สำเร็จ')}}
  if(!selectedClassroom)return <div className="card empty">กรุณาเลือกห้องเรียนก่อน</div>
  return <div className="stack"><div><h1 className="page-title">สไลด์แบบเลื่อนอ่าน — {selectedClassroom.name}</h1><p className="page-subtitle">เลือกภาพหลายหน้า 01.jpg, 02.jpg, 03.jpg… นักเรียนเลื่อนอ่านต่อเนื่องเหมือนการ์ตูน</p></div>{error&&<div className="message message-error">{error}</div>}{progress&&<div className="message message-success">{progress}</div>}<section className="card"><h2 style={{marginTop:0}}>สร้างชุดสไลด์</h2><form className="stack" onSubmit={create}><label>ชื่อสไลด์<input name="title" required placeholder="เช่น การเขียนภาพฉาย — บทที่ 1"/></label><label>คำอธิบาย<textarea name="description" rows={2}/></label><label>ลำดับ<input type="number" name="sortOrder" defaultValue={0}/></label><label>เลือกรูปทุกหน้า<input type="file" name="pages" required multiple accept="image/jpeg,image/png,image/webp"/></label><div className="message message-success">ภาพแต่ละหน้าไม่เกิน 3 MB · ระบบอัปโหลดทีละหน้าเพื่อให้เสถียรบนมือถือ</div><label className="check-label"><input type="checkbox" name="isPublished" defaultChecked/> เผยแพร่ให้นักเรียนทันที</label><button className="btn btn-primary" disabled={loading}>{loading?'กำลังอัปโหลด…':'สร้างสไลด์แบบการ์ตูน'}</button></form></section><section className="card"><h2 style={{marginTop:0}}>ชุดสไลด์ในห้อง</h2>{slides.length?<div className={styles.managerGrid}>{slides.map(s=><article className={styles.slideCard} key={s.id}><h3 style={{margin:'0 0 5px'}}>{s.title}</h3><div className="muted">{s.page_count} หน้า · {s.is_published?'เผยแพร่':'ซ่อน'}</div><div className="row" style={{marginTop:12,flexWrap:'wrap'}}><label className="btn btn-secondary btn-sm" style={{cursor:'pointer'}}>+ เพิ่มหน้า<input type="file" multiple accept="image/jpeg,image/png,image/webp" style={{display:'none'}} onChange={e=>{void addPages(s.id,e.target.files);e.currentTarget.value=''}}/></label><button className="btn btn-danger btn-sm" onClick={()=>remove(s)}>ลบชุด</button></div></article>)}</div>:<div className="empty">ยังไม่มีสไลด์แบบการ์ตูน</div>}</section></div>
}
